"""empty message

Revision ID: 018cde0eb1aa
Revises: d4b48ad08dee
Create Date: 2021-10-16 17:46:11.239179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018cde0eb1aa'
down_revision = 'd4b48ad08dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
