"""empty message

Revision ID: 08008201a4ef
Revises: fed929b5f41a
Create Date: 2021-10-15 19:09:23.276530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08008201a4ef'
down_revision = 'fed929b5f41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=sa.ARRAY(sa.VARCHAR(length=120)),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
