"""empty message

Revision ID: 47989b531a24
Revises: 483fa6718e1b
Create Date: 2021-10-16 18:06:06.430636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47989b531a24'
down_revision = '483fa6718e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
