"""empty message

Revision ID: 483fa6718e1b
Revises: 018cde0eb1aa
Create Date: 2021-10-16 17:46:43.627398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483fa6718e1b'
down_revision = '018cde0eb1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
